package dev.lecignejean.movies;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * This class represents a review in the system.
 * It is a MongoDB document stored in the "reviews" collection.
 * It uses Lombok annotations for boilerplate code reduction.
 */
@Document(collection = "reviews")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Review {
    /**
     * The unique identifier of the review.
     * It is automatically generated by MongoDB.
     */
    @Id
    private ObjectId id;

    /**
     * The body of the review.
     * This is the actual text content of the review.
     */
    private String body;

    /**
     * Constructor for creating a review with only the body.
     * The id will be automatically generated when the review is saved.
     *
     * @param body The body of the review.
     */
    public Review(String body) {
        this.body = body;
    }
}